### ISSUE TITLE
Connecting to the Both Networks

### ISSUE THREAD

**Issue by Siddapa** [innov8rz-ftc-team-11039/TeleDrive#1]
Hey Guys,
   I'm from Team 8813 The Winter Soldiers and we're trying to implement your code while staying at home. In your README.md, we were told to connect the host computer to both the Driver Station and an accessible router. We have an extra wifi dongle as well as an inbuilt wifi card but still have no idea how to connect to two networks at the same time on Windows (we're pretty sure it's impossible). Unless we read your instructions wrong we'd really love some help.

Thanks,
  Team 8813

**Comment by mihir-chauhan** [comment]
Hello Team 8813,

Thank you for trying out TeleDrive!

The host computer has to be connected to the Internet, but instead of connecting to the Driver Station, you will need to connect to the WiFi of the Robot Controller or Control Hub.

To do so, you will need that extra WiFi dongle which allows the computer to connect to another WiFi network. Here's how to connect to two networks at the same time:

Once you have plugged in your WiFi dongle, your WiFi menu would look like this:

![WiFi Menu)](https://user-images.githubusercontent.com/39073758/89082088-da7a3b00-d341-11ea-9a2a-d66b28c647d7.png)

Now, you should see a drop-down where it says "WiFi". When you click on that, there will be a drop-down where you can select which WiFi you want to use. "WiFi" is the inbuilt WiFi card, and the "WiFi 2" is your WiFi dongle.

![WiFi Dropdown](https://user-images.githubusercontent.com/39073758/89082318-79069c00-d342-11ea-8647-880d42cf470b.png)

To connect your dongle to the Robot Controller or Control Hub, click on "WiFi 2" and it will show you the current network connected through your WiFi dongle.

![WiFi 2](https://user-images.githubusercontent.com/39073758/89082413-cdaa1700-d342-11ea-98ca-cefb338efed5.png)

Another option is connecting the computer through Ethernet and connecting to the Robot Controller or Control Hub using the computer's WiFi. 

Hope this helps!

Best Regards,
Mihir Chauhan
Team Captain, Head of Software Division
Innov8rz - FTC Team 11039
www.innov8rz.net

**Comment by Siddapa** [comment]
Wow I never even realized that was a thing. Thanks for the help! Will sure give some feedback when we get to try it out.

**Comment by mihir-chauhan** [comment]
No problem! Thanks again for using TeleDrive!
