### ISSUE TITLE
Robot Not Moving

### ISSUE THREAD

**Issue by Siddapa** [innov8rz-ftc-team-11039/TeleDrive#2]
Hey again!
   I know we just asked for help, but we're kind of stuck again. We tried everything you said but it still won't work. We think it has something to do with our code and not our port forward since the input device from another member's house is showing up in the terminal. I'll link our GitHub repo and we'd love it if you could take a look: https://github.com/ftc-team-8813/SkystoneOff-season

Thanks,
    Team 8813

**Comment by mihir-chauhan** [comment]
Hey Team 8813,

Look's like your link to the GitHub repo says "Page Not Found", maybe this is because your repo is private to external people. 

I would guess that the issue either is with the connection to the robot from the host or the Tele-Op code could be missing the calls to the superclass or the IP address of the Robot Controller or Control Hub may be incorrect. Please also note that the ports have to be consistent between the host computer and the robot as well as from the other driver to your host computer. For example, the host computer can listen to the driver on Port 1234, while the robot and the host computer can communicate on Port 2345, but just make sure they are consistent. Also, please make sure the ports are different as you cannot listen and send to two devices on the same port at the same time.
 
[Check out the README for the integration with your TeleOp](https://github.com/innov8rz-ftc-team-11039/TeleDrive#part-1-integrate-teledrivejava-with-your-existing-teleop-programs) and make sure you have followed all of the steps.

Best Regards,
Mihir Chauhan
Team Captain, Head of Software Division
Innov8rz - FTC Team 11039
www.innov8rz.net

**Comment by mihir-chauhan** [comment]
Hey Team 8813,

Just wanted to check back if everything is functioning correctly with your issue. If the problem isn't solved please let us know.

Best Regards,
Mihir Chauhan
Team Captain, Head of Software Division
Innov8rz - FTC Team 11039
www.innov8rz.net
