### ISSUE TITLE
Driver is not connecting to the Host

### ISSUE THREAD

**Issue by CaydenPocrass** [innov8rz-ftc-team-11039/TeleDrive#3]
Hi, thanks for sharing this tool with everyone!  We were having a spot of difficulty in connecting the driver to the host after following the directions in the readme.  The gamepad telemetry appears on the driver terminal, but not on the host terminal.  The IP address on TeleDrive.java is the same one that is on the robot controller, with the port configured on TeleDrive being the same one on the robot controller.  The port used by the host is the same as the one configured when setting up port forwarding and does not indicate that it is already occupied.  The driver was unable to connect to either the ip address found in the host computer's network settings and at the "listening on local port:" message, nor to the different ip address shown in the terminal by the "to drive the robot, connect to " message, both at the port set in the port forwarding process as the host port.  We were testing this on a clean sdk, using the super. functions in the pushbot sample code.  We're at a loss for what to do next, and would love it if you could help us with this.

**Comment by mihir-chauhan** [comment]
Hey Cayden,

Thank you for trying out TeleDrive!

Are you trying to run this locally (the Driver and Host are on the same WiFi router) or is it being run remotely (Driver is in another place / different WiFi router than the Host)?

Here are a couple of things you could try.

First, you can try pinging the public IPv4 of the Host computer from the Driver computer at the specific port by going to http://check-host.net/check-udp. If it says `Open or filtered` as a result of at least one of the server locations, that means that your port forwarding is correct. Otherwise, please check your public IPv4 at https://www.whatismyip.com/. Please make sure to double-check that the port forwarding port and IP address are consistent.

Another option is to try using TeleDrive over the same WiFi network where the Host computer is on the same network as the Driver computer. Run through the same process, but instead of connecting the Driver to the Host's public IP address, use the Host's local IP address. Just make sure they are on the same WiFi network, otherwise, it wouldn't work.

Hope this helps!

Best Regards,
Mihir Chauhan
Team Captain, Head of Software Division
Innov8rz - FTC Team 11039
www.innov8rz.net

**Comment by mihir-chauhan** [comment]
Hey Cayden,

Just wanted to check back if everything is functioning correctly with your issue. If the problem isn't solved please let us know.

Best Regards,
Mihir Chauhan
Team Captain, Head of Software Division
Innov8rz - FTC Team 11039
www.innov8rz.net
